# Generated by Django 3.2.7 on 2021-09-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=80)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('oxygen', models.FloatField(default=0)),
                ('hydrogen', models.FloatField(default=0)),
                ('salt', models.FloatField(default=0)),
                ('turbidity', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
