# Generated by Django 3.2.7 on 2021-09-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environ', '0003_auto_20210909_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='environ',
            name='ocean',
            field=models.CharField(default='none', max_length=80),
        ),
    ]
