# Generated by Django 3.2.7 on 2021-09-10 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('environ', '0004_environ_ocean'),
    ]

    operations = [
        migrations.AddField(
            model_name='environ',
            name='measurement_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
