# Generated by Django 3.2.7 on 2021-09-11 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buoys', '0009_auto_20210910_0825'),
        ('environ', '0005_environ_measurement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environ',
            name='buoy_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environ', to='buoys.buoy'),
        ),
    ]
