# Generated by Django 3.2.7 on 2021-09-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environ', '0006_alter_environ_buoy_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environ',
            old_name='buoy_data',
            new_name='odn_data',
        ),
    ]
