# Generated by Django 4.0a1 on 2021-09-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environ', '0007_rename_buoy_data_environ_odn_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environ',
            old_name='lon',
            new_name='lng',
        ),
    ]
