# Generated by Django 4.0a1 on 2021-09-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environ', '0008_rename_lon_environ_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environ',
            name='location',
        ),
    ]
