# Generated by Django 4.0a1 on 2021-09-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environ', '0009_remove_environ_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='environ',
            name='area1',
            field=models.CharField(default='none', max_length=80),
        ),
        migrations.AddField(
            model_name='environ',
            name='area2',
            field=models.CharField(default='none', max_length=80),
        ),
        migrations.AddField(
            model_name='environ',
            name='area3',
            field=models.CharField(default='none', max_length=80),
        ),
        migrations.AddField(
            model_name='environ',
            name='area4',
            field=models.CharField(default='none', max_length=80),
        ),
        migrations.AddField(
            model_name='environ',
            name='area5',
            field=models.CharField(default='none', max_length=80),
        ),
    ]
