# Generated by Django 4.0a1 on 2021-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environ', '0010_environ_area1_environ_area2_environ_area3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environ',
            name='area1',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='environ',
            name='area2',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='environ',
            name='area3',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='environ',
            name='area4',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='environ',
            name='area5',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
