# Generated by Django 4.0a1 on 2021-09-24 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environ', '0011_alter_environ_area1_alter_environ_area2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environ',
            name='area5',
        ),
    ]
