# Generated by Django 3.2.6 on 2021-08-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210831_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='Unnamed User', max_length=30, verbose_name='name'),
        ),
    ]
