# Generated by Django 3.2.6 on 2021-08-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210831_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='smartbuoy',
            new_name='buoyuser',
        ),
    ]
