# Generated by Django 3.2.7 on 2021-09-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoys', '0003_auto_20210831_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='buoy',
            name='hydrogen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='buoy',
            name='oxygen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='buoy',
            name='salt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='buoy',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='buoy',
            name='turbidity',
            field=models.FloatField(default=0),
        ),
    ]
