# Generated by Django 3.2.7 on 2021-09-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys', '0007_auto_20210908_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buoy',
            old_name='x',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='buoy',
            old_name='y',
            new_name='lon',
        ),
    ]
